services:
  aggregator:
    environment:
      DATA_MODE: production
      HOST: 0.0.0.0
      PORT: 8766
      PRODUCTION_CONFIG: /app/backend/production.local.json
      MATOMO_URL: https://matomo.istanapresiden.go.id
      MATOMO_TOKEN_AUTH: 3661d419ce3be50613490646ca8e2574
      PROMETHEUS_URL: https://192.168.32.247:30443
      PROMETHEUS_BEARER_TOKEN: uk2_xLM8CfhIizcHbmTAYG4L1sGufsJBWbZqQtjsPAc6
      SIGNOZ_URL: https://192.168.32.247:30444
      SIGNOZ_API_KEY: yHsIv9EK7EZi0DcCK38B4kEovI/wBTBv8EBufOulngg=
      SUPERSET_URL: https://superset-dev.setneg.go.id
      SUPERSET_REFRESH_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc5MDIyMjk0NSwianRpIjoiZmI0ZTk3NGItNDkyNy00ZDIwLWI1ZDctNzFhYjM0YzllMGE1IiwidHlwZSI6InJlZnJlc2giLCJzdWIiOjQsIm5iZiI6MTc5MDIyMjk0NSwiY3NyZiI6ImNmMjY1MTM3LWJkMjktNGY5ZC1iNTJjLTUzY2NiYmM0ZTc3MyIsImV4cCI6MTc5MjgxNDk0NX0.j7tqwLsiEEjp5Je1rjJY-rb9OtrZXVbaUKSkc9VHwFk"
    volumes:
      - ../backend/production.local.json:/app/backend/production.local.json:ro