pageInfo:
  title: Executive Observability
  description: Portal monitoring manajemen
appConfig:
  theme: nord-frost
  layout: auto
  iconSize: small
sections:
  - name: Executive overview
    items:
      - title: Management dashboard
        url: https://monitor.example.org
        target: newtab
  - name: Dashboard sumber
    items:
      - title: SigNoz
        url: http://192.168.32.247:30080/dashboard
        target: newtab
      - title: Uptime Kuma
        url: http://192.168.32.247:30081/status/production
        target: newtab
      - title: Matomo
        url: https://matomo.istanapresiden.go.id
        target: newtab
      - title: Superset
        url: https://superset-dev.setneg.go.id/superset/dashboard/executive/
        target: newtab

